---

R1:
    hostname: "192.168.0.1"
    interfaces:
        GigabitEhternet0/0:
            ip: "192.168.1.1"
            description: "Management"
        Loopback0:
            ip: "10.1.1.1"
            description: "Loopback"
    data:
        bgp:
            asn: 100
            router_id: 1.1.1.1
            neighbors:
                - name: {{ name }}
                  ip: 10.10.1.50
                  ipv6: 2001:db8:1::1
                  remote_as:
