---

R1:
    interfaces:
        GigabitEhternet0/0:
            ip: "192.168.1.1"
            description: "Management"
        Loopback0:
            ip: "10.1.1.1"
            description: "Loopback"
    data:
        bgp:
            as: 100
            router_id: 1.1.1.1
            neighbors:
                - name: {{ name }}
                  ip: {{ ipaddr4 }}
                  ipv6: {{ ipaddr6 }}
                  asn: {{ asn }}
